Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  
  config.vm.provider :virtualbox do |vb|
    vb.name = "rbe3002-vagrant-vm"
    vb.gui = true

    # Set RAM (in MB)
    vb.memory = 4096  # 4 GB
    
    # Set CPU cores
    vb.cpus = 2
  end
  config.disksize.size = '50GB'
end
